/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegionalRouteImport } from './routes/regional'
import { Route as OlsRouteImport } from './routes/ols'
import { Route as MonteCarloRouteImport } from './routes/monte-carlo'
import { Route as MalmquistRouteImport } from './routes/malmquist'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as GarchRouteImport } from './routes/garch'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DmmRouteImport } from './routes/dmm'
import { Route as DigitalServicesRouteImport } from './routes/digital-services'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalRoute = RegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => rootRouteImport,
} as any)
const OlsRoute = OlsRouteImport.update({
  id: '/ols',
  path: '/ols',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteCarloRoute = MonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => rootRouteImport,
} as any)
const MalmquistRoute = MalmquistRouteImport.update({
  id: '/malmquist',
  path: '/malmquist',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const GarchRoute = GarchRouteImport.update({
  id: '/garch',
  path: '/garch',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DmmRoute = DmmRouteImport.update({
  id: '/dmm',
  path: '/dmm',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalServicesRoute = DigitalServicesRouteImport.update({
  id: '/digital-services',
  path: '/digital-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/digital-services': typeof DigitalServicesRoute
  '/dmm': typeof DmmRoute
  '/forecast': typeof ForecastRoute
  '/garch': typeof GarchRoute
  '/infrastructure': typeof InfrastructureRoute
  '/malmquist': typeof MalmquistRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/ols': typeof OlsRoute
  '/regional': typeof RegionalRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/digital-services': typeof DigitalServicesRoute
  '/dmm': typeof DmmRoute
  '/forecast': typeof ForecastRoute
  '/garch': typeof GarchRoute
  '/infrastructure': typeof InfrastructureRoute
  '/malmquist': typeof MalmquistRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/ols': typeof OlsRoute
  '/regional': typeof RegionalRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/digital-services': typeof DigitalServicesRoute
  '/dmm': typeof DmmRoute
  '/forecast': typeof ForecastRoute
  '/garch': typeof GarchRoute
  '/infrastructure': typeof InfrastructureRoute
  '/malmquist': typeof MalmquistRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/ols': typeof OlsRoute
  '/regional': typeof RegionalRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/digital-services'
    | '/dmm'
    | '/forecast'
    | '/garch'
    | '/infrastructure'
    | '/malmquist'
    | '/monte-carlo'
    | '/ols'
    | '/regional'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/digital-services'
    | '/dmm'
    | '/forecast'
    | '/garch'
    | '/infrastructure'
    | '/malmquist'
    | '/monte-carlo'
    | '/ols'
    | '/regional'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/digital-services'
    | '/dmm'
    | '/forecast'
    | '/garch'
    | '/infrastructure'
    | '/malmquist'
    | '/monte-carlo'
    | '/ols'
    | '/regional'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DigitalServicesRoute: typeof DigitalServicesRoute
  DmmRoute: typeof DmmRoute
  ForecastRoute: typeof ForecastRoute
  GarchRoute: typeof GarchRoute
  InfrastructureRoute: typeof InfrastructureRoute
  MalmquistRoute: typeof MalmquistRoute
  MonteCarloRoute: typeof MonteCarloRoute
  OlsRoute: typeof OlsRoute
  RegionalRoute: typeof RegionalRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional': {
      id: '/regional'
      path: '/regional'
      fullPath: '/regional'
      preLoaderRoute: typeof RegionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ols': {
      id: '/ols'
      path: '/ols'
      fullPath: '/ols'
      preLoaderRoute: typeof OlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-carlo': {
      id: '/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof MonteCarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malmquist': {
      id: '/malmquist'
      path: '/malmquist'
      fullPath: '/malmquist'
      preLoaderRoute: typeof MalmquistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garch': {
      id: '/garch'
      path: '/garch'
      fullPath: '/garch'
      preLoaderRoute: typeof GarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmm': {
      id: '/dmm'
      path: '/dmm'
      fullPath: '/dmm'
      preLoaderRoute: typeof DmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-services': {
      id: '/digital-services'
      path: '/digital-services'
      fullPath: '/digital-services'
      preLoaderRoute: typeof DigitalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DigitalServicesRoute: DigitalServicesRoute,
  DmmRoute: DmmRoute,
  ForecastRoute: ForecastRoute,
  GarchRoute: GarchRoute,
  InfrastructureRoute: InfrastructureRoute,
  MalmquistRoute: MalmquistRoute,
  MonteCarloRoute: MonteCarloRoute,
  OlsRoute: OlsRoute,
  RegionalRoute: RegionalRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
